export const publicRoutes = [
  '/login',
  '/register',
  '/register/success',
  '/',
  '/unauthorized',
  '/about',
  '/loans',
  '/savings',
  '/eajo',
  '/help-center',
  '/privacy-policy',
  '/terms-of-service',
  '/contact-us',
  '/faq',
]
