import type { Metadata } from 'next'
import { Geist_Mono, Inter, Manrope } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import I18nProvider from '@/providers/I18nProvider'
import StoreProvider from '@/providers/StoreProvider'
import { SessionProvider } from 'next-auth/react'
import { Toaster } from '@/components/ui/sonner'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })
const manrope = Manrope({ subsets: ['latin'], variable: '--font-manrope' })

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang='en'
      className={cn(
        'h-full',
        'antialiased',
        geistMono.variable,
        'font-sans',
        inter.variable,
        manrope.variable,
      )}
      suppressHydrationWarning
    >
      <body className='min-h-full flex flex-col'>
        <SessionProvider>
          <StoreProvider>
            <I18nProvider>
              {children}
              <Toaster position='top-left' duration={5000} />
            </I18nProvider>
          </StoreProvider>
        </SessionProvider>
      </body>
    </html>
  )
}
